### ISSUE TITLE
Choose name for the app

### ISSUE THREAD

**Issue by Jkutkut** [jkutkutOrg/Android-CineHub#1]
Here are some suggestions:

- Cinematick
- Ticketwise
- CineMaven
- ShowTracker
- MovieMate
- FlickFiler
- BoxOfficeBoss
- FilmFrenzy
- CineHub
- ScreenSavvy
- CinemaFlow
- MovieMaster
- SeatSquad
- FilmFixer
- TicketTrove
- CinemaCraze
- FilmFanatic
- ShowSavant
- CineStream
- MovieMania

**Comment by Jkutkut** [comment]
I like CineHub 😃

**Comment by alexaib2002** [comment]
What about **FilmHub**? Sounds more marketable 👍

**Comment by Jkutkut** [comment]
> What about **FilmHub**? Sounds more marketable 👍

I like it too. However, the name "CineHub" has meaning both in spanish and english. Therefore, I believe it is actually this one the one marketable.

**Comment by alexaib2002** [comment]
> > What about **FilmHub**? Sounds more marketable +1
> 
> I like it too. However, the name "CineHub" has meaning both in spanish and english. Therefore, I believe it is actually this one the one marketable.

Well, CineHub sounds well too, but I think FilmHub sounds better. Still, I wouldn't have any problem at all with either of those names. Feel free to close this issue at anytime, with the one you prefer the most

**Comment by Jkutkut** [comment]
I feel the same. Let's make @alexeses be the one to choose.

**Comment by aleexgheorghe** [comment]
> I feel the same. Let's make @alexeses be the one to choose.

Both options are equally valid, I think **CineHub** may sell better.

I would use FilmHub in case in the application you can get to view movies, film = movie? 

CineHub refers to a cinema, the place where you are going to watch the movie. Our application will be in charge of booking the tickets to access the cinema.

Thank you for considering me!

**Comment by alexaib2002** [comment]
Alright, CineHub will be then! I'm closing this issue as now we have an official app name.
