### ISSUE TITLE
Seat selection

### ISSUE THREAD

**Issue by alexaib2002** [jkutkutOrg/Android-CineHub#10]
## About
This activity should prompt the user which seat they want to choose.
The "Screen" TextView should be treated as a placeholder, and it could be replaced with an ImageView on future versions. If we keep this TextView, it should use the secondary color of the app's theme.

## Ongoing data
- Encoded room layout (bidimentional character array with characters encoding which seats are currently occupied)
- Room id (required for formatting the name of the room)

## Outgoing data
- Selected seat position (row, col)
- Room id (required so we know at which room the seat will be booked)

## Entry activity
- Users will always enter from #14 

## Exit activity
- Users will always exit at #11 

## Draft
![image](https://user-images.githubusercontent.com/66980937/224067435-d87914d1-bb70-4307-9a97-9c092325c373.png)

**Comment by alexaib2002** [comment]
I'll detail the room encoding in a new issue, please stay tuned 😉

**Comment by alexaib2002** [comment]
Multi seat selection implemented! What do you think @alexeses @Jkutkut ?
![image](https://user-images.githubusercontent.com/66980937/224563166-7c035f55-c613-4f0c-b45e-5e15323cccc4.png)

**Comment by aleexgheorghe** [comment]
I think it is very nice!

**Comment by alexaib2002** [comment]
- Activity fully implemented by #38, closing issue
