### ISSUE TITLE
Logo selection - Discussion

### ISSUE THREAD

**Issue by aleexgheorghe** [jkutkutOrg/Android-CineHub#15]
Hi team ✋🏼 !

The project looks amazing, but we must not forget about the branding of the project. What do you have in mind for the logo? I have made a sketch that could be a very good option. Let me know your feedback! ([proofs](https://user-images.githubusercontent.com/46347629/223215253-40c9c86b-d9f3-462a-956f-41809733cfaf.png))

What do you think?
![1](https://user-images.githubusercontent.com/46347629/223215535-edfc532c-385c-460a-a415-f0474167c324.png)
![2](https://user-images.githubusercontent.com/46347629/223215628-8925a22e-b2e8-40e3-92fb-9cfab46b1a34.png)

**Comment by alexaib2002** [comment]
Looks great! Despite being an early sketch, it already looks very polished. Still, if we're going to make a logo, I think it would also make sense adding an app icon.

**Comment by aleexgheorghe** [comment]
In the next pull request the logo will be implemented in both formats. Thanks for your feedback!
