### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by aleexgheorghe** [jkutkutOrg/Android-CineHub#16]
Hi guys!

I open this issue in order to discuss among all the members of the team about the database data and the structure of this same, so we can save time!

Functionalities:

1. Authentication system
   1. Login: mail, password
   2. Registration: first name, mail, password
2. Display of movies
   1. Name of the movie
   2. Short description
   3. Date and time of the movie
   4. Room of the movie
   5. Banner of the movie
   6. Price of the movie

We must take into account if the movie room is available, the number of reservations of the room should not exceed the maximum number of seats available in the room.

The movies can contain a unique ID, this way we can synchronize it with the banner. What do you think?

Open debate!

**Comment by Jkutkut** [comment]
Is the first-name of the user really needed ? I don't think it will be used anywhere and it will imply creating a data source with the user information.

**Comment by aleexgheorghe** [comment]
> Is the first-name of the user really needed ? I don't think it will be used anywhere and it will imply creating a data source with the user information.

I was planning to save the client's name to reference it in a much clearer way ("Welcome ${name}" or  "Thanks for your reservation ${name}). What do you think @alexaib2002?

**Comment by alexaib2002** [comment]
> > Is the first-name of the user really needed ? I don't think it will be used anywhere and it will imply creating a data source with the user information.
> 
> I was planning to save the client's name to reference it in a much clearer way ("Welcome name"or"Thanksforyourreservation{name}). What do you think @alexaib2002?

Following our main goal of keeping everything as simple as possible, I think we should discard the first name of the user, as said by @Jkutkut, or else we may end up over-engineering our DB.

**Comment by Jkutkut** [comment]
@alexeses @alexaib2002 please take a look a the [branch of this issue](https://github.com/jkutkutOrg/Android-CineHub/blob/wip-database_model/docs/database_model.md). I have defined the first iteration of the database. Let me know what do you think.

@alexeses I have good news for you: the addition of the user in the current state of the DB adds little more complexity. Therefore, it is added for now.

**Comment by alexaib2002** [comment]
> @alexeses @alexaib2002 please take a look a the [branch of this issue](https://github.com/jkutkutOrg/Android-CineHub/blob/wip-database_model/docs/database_model.md). I have defined the first iteration of the database. Let me know what do you think.

Looks fine to me, but as a minor objection, do we really need giving each `Room` a name? With the `id`, we could generate the room's name on the client (so rooms would be named as: "Room 1" , "Room 2", ...).

**Comment by Jkutkut** [comment]
> > @alexeses @alexaib2002 please take a look a the [branch of this issue](https://github.com/jkutkutOrg/Android-CineHub/blob/wip-database_model/docs/database_model.md). I have defined the first iteration of the database. Let me know what do you think.
> 
> Looks fine to me, but as a minor objection, do we really need giving each `Room` a name? With the `id`, we could generate the room's name on the client (so rooms would be named as: "Room 1" , "Room 2", ...).

Thank you for the feedback. I agree with you, it can be done in client. Once the model is done, we will see if it is really needed or can be omitted.
