### ISSUE TITLE
Encoded room layouts

### ISSUE THREAD

**Issue by alexaib2002** [jkutkutOrg/Android-CineHub#22]
# The problem
SeatSelectionActivity requires an "Encoded Room Layout" for working properly. 
This is, a two-dimensional array containing a set of characters defining the state of the seats located on the room. The current characters are the following:
- `f`: Free seat, can be selected by the user, tinted with greenish color 
- `o`: Occupied seat, cannot be selected by the user, tinted with reddish color
- ` `: Non-existent seat, used for defining the room's structure

The array should be made out of `Character` objects, as they implement the `Serializable` interface and can be moved between activities with ease.

An example of the layout would be the following
|Encoded room|Rendered room|
|----|----|
|![image](https://user-images.githubusercontent.com/66980937/224074122-2c47cce2-de0a-46cc-b3a0-eec63f492156.png)|![image](https://user-images.githubusercontent.com/66980937/224073695-a7a80fd8-762f-41c2-8f8f-26ca14d114ef.png)|

# How to

With that out of the way, multiple problems arise:
- *How should we store this layouts?*: Our db model provides a way to keep track of users' bookings, but there's no way to know which seats are Non-existent, so we should change our model (#16) or ignore this feature completely.
- *Rooms must be parsed before entering SeatSelectionActivity**: This means, after the user has selected a film at #14, but before entering #10, we must generate the Encoded Room Layout containing all the existing seats.

**Comment by Jkutkut** [comment]
You want it? You got it. I'll reopen the issue and start working on it now.

**Comment by alexaib2002** [comment]
> You want it? You got it. I'll reopen the issue and start working on it now.

Thanks for answering quickly 😉! I'll keep this issue open until the DB supports this feature and its query is implemented.
