### ISSUE TITLE
Database enhancements

### ISSUE THREAD

**Issue by Jkutkut** [jkutkutOrg/Android-CineHub#25]
All small - non breaking features or changes to the database can be listed here. They will be implemented in the future.

**Comment by Jkutkut** [comment]
- change the `state` attribute to `type` for better cohesiveness with the client's code (by @alexaib2002 in #23 ).

**Comment by Jkutkut** [comment]
- `room_configuration` or `seat_reservation`?

**Comment by alexaib2002** [comment]
> * `room_configuration` or `seat_reservation`?

`room_configuration` fits the purpose of the component better

**Comment by Jkutkut** [comment]
All enhancements until this point implemented in the current iteration of the #19
