### ISSUE TITLE
DB data filtering implementation

### ISSUE THREAD

**Issue by alexaib2002** [jkutkutOrg/Android-CineHub#29]
Currently, #28 can only query all data available on DB. Specific registers will be required for implementing several activities (ex: #10 needs all the seat reservations made on the selected `Room`, so the only way to do it is filtering the server result on the client, not very efficient...). 

Should we keep using this way of querying the DB or should the API expose methods for specific queries?

**Comment by Jkutkut** [comment]
@alexaib2002 
As we talk yesterday, the reason the API only allows (for now) to query all data, is just so you can start testing with data from the DB. As you know, we have #6 to define the features that our app will have (but it is not defined yet). Furthermore, the issue #19 is still awaiting both you and @alexeses to define what do you need so I can start working on those methods.

Once those are defined, I plan for the API to be able to query specific data making use of the non-sql nature of it. Until then, I can only give you generic-querry-all methods. Sorry if that is an inconvenience.
