### ISSUE TITLE
Get encoded room layout for given RoomId

### ISSUE THREAD

**Issue by alexaib2002** [jkutkutOrg/Android-CineHub#34]
**What does this method do?**
Returns the encoded layout (#22) for the corresponding `RoomId`

**Input**
The `roomId` of the required room.

**Output**
`Character[][]`

**Additional info**
- This method should be implemented instead of #31, so I can keep the original code structure.

**Comment by Jkutkut** [comment]
Implemented with the version db-v0.9.01 (see #19)
