### ISSUE TITLE
Full data insertion method

### ISSUE THREAD

**Issue by alexaib2002** [jkutkutOrg/Android-CineHub#35]
**What does this method do?**
Inserts a `SeatReservation`, with its corresponding `Reservation` onto the database. 

**Input**
Both the `SeatReservation` and the `Reservation` containing the `user_id`.

**Output**
None (at least usable data)

**Additional info**
It would be useful having `onSuccess` and `onFailiure` callbacks to handle the DB response.

**Comment by Jkutkut** [comment]
@alexaib2002 Are we going to implement the multiple-seat reservation feature? Last time we discussed this we were awaiting to see how the project grow.
I believe it would be awesome to have this feature.

**Comment by alexaib2002** [comment]
> @alexaib2002 Are we going to implement the multiple-seat reservation feature? Last time we discussed this we were awaiting to see how the project grow. I believe it would be awesome to have this feature.

Actually, given the current status of the project, it seems very plausible to me. Also, it wouldn't be that much of a change implementing support for it on both `SeatSelectionActivity` and `BookingSummaryActivity`. What do you think @alexeses?

**Comment by aleexgheorghe** [comment]
As you indicate @alexaib2002, the project is in a very advanced state. I would give the go-ahead!

**Comment by alexaib2002** [comment]
Ok then, I've already started implementing it on #10

**Comment by alexaib2002** [comment]
Reopening issue, as the requested method was still not implemented

**Comment by alexaib2002** [comment]
@Jkutkut any updates on this issue?

**Comment by Jkutkut** [comment]
Method fully implemented in `db-v0.9.04`
