### ISSUE TITLE
Submit code 

### ISSUE THREAD

**Issue by Jkutkut** [jkutkutOrg/Android-CineHub#4]
https://campus.europaeducationgroup.es/courses/33195/assignments/198541?module_item_id=712300

**Comment by aleexgheorghe** [comment]
All the documents required for the project presentation will be uploaded to the shared [drive folder](https://drive.google.com/drive/u/0/folders/1-tweV-zEiw3NQHLmh1iicGcbXmfPyLC-), so that we can all contribute.

**Comment by Jkutkut** [comment]
> All the documents required for the project presentation will be uploaded to the shared [drive folder](https://drive.google.com/drive/u/0/folders/1-tweV-zEiw3NQHLmh1iicGcbXmfPyLC-), so that we can all contribute.

What about using the wiki page? It's integrated with the repository and allows to work with it like a repository
