### ISSUE TITLE
BUG - On buy ticket

### ISSUE THREAD

**Issue by aleexgheorghe** [jkutkutOrg/Android-CineHub#54]
Case:

A new user registers, tries to purchase a movie and when selecting seats selects two or more, upon checkout in the main menu he is assigned duplicate tickets.

After testing this, I have tried to purchase a single ticket of another movie, it is added duplicate but with the same name as the previous ones. [Video](https://drive.google.com/file/d/1z9XgViPUz0sG1MGbX0IPTE6w3cSYLn8S/view?usp=share_link)

Please, if someone starts working on this BUG react to the issue.

**Comment by alexaib2002** [comment]
I'll try to debug and analyze further the cause of the issue.

**Comment by alexaib2002** [comment]
`main` doesn't present this problem, but another one; it doesn't recognize which movie has been actually clicked. Because of our time constraints, I'll try to fix the bug directly at #53

**Comment by Jkutkut** [comment]
Is this fixed then? @alexaib2002 @alexeses
