### ISSUE TITLE
Docs - App features

### ISSUE THREAD

**Issue by Jkutkut** [jkutkutOrg/Android-CineHub#6]
Let's discuss the features of the App.

This issue should be closed once a document in the wiki has been filled.

**Comment by Jkutkut** [comment]
It should make use of firebase:

- [x] Login system (email + password).
- [x] Realtime database to store the data.
- [ ] Storage (Not sure if needed).

**Comment by Jkutkut** [comment]
I don't think a backend is needed in this case:
- The app will be able to read from Firebase.
- The app will add some information to Firebase.

Therefore, I don't think we need to compute anything else outside the client app.

**Comment by Jkutkut** [comment]
Does the app have a root/admin mode?

Not having it will make most of the DB way faster to develop (there will be just some initial data).

**Comment by alexaib2002** [comment]
> Does the app have a root/admin mode?
> 
> Not having it will make most of the DB way faster to develop (there will be just some initial data).

I don't think it should have one, as this app is just a client for the DB and not a management tool. I mean, the admins should have direct access to the Firebase console, right?

**Comment by Jkutkut** [comment]
Right, makes perfect sense!

**Comment by Jkutkut** [comment]
At this point, this issue can be closed XD
