### ISSUE TITLE
Establish Git branch naming conventions

### ISSUE THREAD

**Issue by alexaib2002** [jkutkutOrg/Android-CineHub#9]
We should all agree a convention for naming our branches. My proposal would be the following:

1. **Branch type first**, followed by a hyphen (-):
   - `wip` Work in progress branches
   - `dev` Our own branches (the ones where we could merge small changes without affecting the others)
   - `rel` Release branch, the one where everything should work

2. **Feature identifier** (snake_case): What will this branch bring to the project

An example of this would be the following branch:
`wip-my_buggy_feature`

After closing this issue, the final convention should be merged on the project wiki.

Any ideas or suggestions are appreciated!

**Comment by Jkutkut** [comment]
I don't understand is the `rel` one. What is the difference  between `rel` and the main branch?

**Comment by Jkutkut** [comment]
I have a doubt with the issues with branches: If I create a branch from a issue, it should be `dev-name_of_issue`, `wip-name_of_issue` or `name-of-issue` (the default name generated by GitHub.

**Comment by alexaib2002** [comment]
> I don't understand is the `rel` one. What is the difference between `rel` and the main branch?

Main branch will be where all `dev` branches would be merged to. As it's currently protected, it would require reviews from all participants of the project.
On the other hand, `rel` branch will only contain "bug-free" commits. Thus, releases of the project would be made out of `rel` branch.

**Comment by alexaib2002** [comment]
> I have a doubt with the issues with branches: If I create a branch from a issue, it should be `dev-name_of_issue`, `wip-name_of_issue` or `name-of-issue` (the default name generated by GitHub.

With this naming scheme, I think `wip-name_of_issue` works better:

Note that a feature that I would like to implement, like "Data querying implementation", may contain several issues (like "Implement database authentication", "Implement database query displays on X activity", ...). 

Given this example, we would have the following branches:

- `dev-data_query_implementation` (I would be the owner of this branch)
- `wip-database_auth` 
- `wip-database_dislpay`

My `wip` branches would be merged onto my `dev` branch, and afterwards I would require a review from everyone before my `dev` branch may finally be merged onto the `main` one.

**Comment by Jkutkut** [comment]
> > I have a doubt with the issues with branches: If I create a branch from a issue, it should be `dev-name_of_issue`, `wip-name_of_issue` or `name-of-issue` (the default name generated by GitHub.
> 
> With this naming scheme, I think `wip-name_of_issue` works better:
> 
> Note that a feature that I would like to implement, like "Data querying implementation", may contain several issues (like "Implement database authentication", "Implement database query displays on X activity", ...).
> 
> Given this example, we would have the following branches:
> 
> * `dev-data_query_implementation` (I would be the owner of this branch)
> * `wip-database_auth`
> * `wip-database_dislpay`
> 
> My `wip` branches would be merged onto my `dev` branch, and afterwards I would require a review from everyone before my `dev` branch may finally be merged onto the `main` one.

That makes perfect sense. I will try to follow this as much as possible  😄

**Comment by alexaib2002** [comment]
Great! Then I'll close this issue and merge this onto the wiki ASAP 👍
